"""
Box-backed store for AFM cell records.

Why Box rather than a spreadsheet: a spreadsheet holds rows but not files, and
every cell here comes with a force curve, a video and a thumbnail. Box holds
all of it in one place, and UC Davis gives it away.

Layout, one folder per cell::

    <root>/
        index.csv                     rebuildable cache of every record
        cells/
            <cell_id>/
                record.json           metadata and fit, the source of truth
                curve.csv             relative_deformation, force_N
                thumbnail.png         one frame showing the cell's morphology
                video.mp4             optional

``record.json`` is authoritative and ``index.csv`` is only a cache, so a
corrupted or stale index is never data loss: :meth:`BoxStore.rebuild_index`
walks the folders and writes a new one. That matters because two people saving
at once would otherwise race on a single shared file.

Authentication
--------------
Box offers several ways in, and which are available depends on the Box admin,
so this accepts all of them and uses whichever is configured. In order of
preference:

1. **Client Credentials Grant** (``client_id``, ``client_secret``, and one of
   ``enterprise_id`` or ``user_id``). Tokens refresh themselves, so this keeps
   working unattended. On an enterprise account like UC Davis the app usually
   needs admin authorisation before its first use.
2. **OAuth refresh token** (``client_id``, ``client_secret``,
   ``refresh_token``). You authorise once as yourself. Box rotates the refresh
   token on every use, so the new one has to be written back somewhere, which
   makes this awkward on a read-only deployment.
3. **Developer token** (``developer_token``). Generated by hand in the Box
   developer console and valid for one hour. Good for trying this out, useless
   for daily work.

Put whichever you have in ``.streamlit/secrets.toml``::

    [box]
    client_id = "..."
    client_secret = "..."
    enterprise_id = "..."      # or user_id
    root_folder_id = "123456"  # the folder to store cells in, 0 = All Files
"""

from __future__ import annotations

import io
import json
import mimetypes
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid

API = "https://api.box.com/2.0"
UPLOAD_API = "https://upload.box.com/api/2.0"
TOKEN_URL = "https://api.box.com/oauth2/token"


class BoxError(RuntimeError):
    """Raised with a message meant to be shown to the user as-is."""


class BoxStore:
    """Minimal Box client covering exactly what this app needs."""

    def __init__(self, config=None, root_folder_id="0"):
        self.config = dict(config or {})
        self.root_folder_id = str(
            self.config.get("root_folder_id") or root_folder_id or "0"
        )
        self._token = None
        self._token_expires = 0.0
        self._folder_cache = {}

    # ------------------------------------------------------------- auth

    def auth_method(self):
        """Which credential set is configured, or None."""
        cfg = self.config
        if cfg.get("client_id") and cfg.get("client_secret"):
            if cfg.get("enterprise_id") or cfg.get("user_id"):
                return "client_credentials"
            if cfg.get("refresh_token"):
                return "refresh_token"
        if cfg.get("developer_token"):
            return "developer_token"
        return None

    def token(self):
        """A valid access token, fetching or refreshing as needed."""
        method = self.auth_method()
        if method is None:
            raise BoxError(
                "No Box credentials configured. Add a [box] section to "
                "`.streamlit/secrets.toml` with either client_id + client_secret "
                "+ enterprise_id, or a developer_token for a quick test."
            )

        if method == "developer_token":
            return self.config["developer_token"]

        if self._token and time.time() < self._token_expires - 60:
            return self._token

        if method == "client_credentials":
            data = {
                "grant_type": "client_credentials",
                "client_id": self.config["client_id"],
                "client_secret": self.config["client_secret"],
            }
            if self.config.get("enterprise_id"):
                data["box_subject_type"] = "enterprise"
                data["box_subject_id"] = str(self.config["enterprise_id"])
            else:
                data["box_subject_type"] = "user"
                data["box_subject_id"] = str(self.config["user_id"])
        else:
            data = {
                "grant_type": "refresh_token",
                "refresh_token": self.config["refresh_token"],
                "client_id": self.config["client_id"],
                "client_secret": self.config["client_secret"],
            }

        request = urllib.request.Request(
            TOKEN_URL,
            data=urllib.parse.urlencode(data).encode(),
            headers={"Content-Type": "application/x-www-form-urlencoded"},
        )
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                payload = json.loads(response.read().decode())
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "ignore")[:400]
            raise BoxError(self._explain_auth_error(exc.code, detail, method)) from exc

        self._token = payload["access_token"]
        self._token_expires = time.time() + float(payload.get("expires_in", 3600))
        if payload.get("refresh_token"):
            # Box rotates refresh tokens; keep the new one for this session at
            # least, or the next call fails with the old one.
            self.config["refresh_token"] = payload["refresh_token"]
        return self._token

    @staticmethod
    def _explain_auth_error(code, detail, method):
        if code in (400, 401, 403):
            if "unauthorized_client" in detail or "access_denied" in detail:
                return (
                    "Box refused the credentials. On an enterprise account the app "
                    "must be authorised by a Box admin before its first use: in the "
                    "Box developer console open your app, then Authorization, then "
                    "Review and Submit. A UC Davis Box admin approves it from "
                    "Admin Console, Enterprise Settings, Platform Apps."
                )
            return f"Box rejected the credentials ({code}): {detail}"
        return f"Box authentication failed ({code}): {detail}"

    def check(self):
        """Confirm the credentials work and the root folder is reachable."""
        who = self._request("GET", f"{API}/users/me")
        folder = self._request("GET", f"{API}/folders/{self.root_folder_id}")
        return {
            "login": who.get("login") or who.get("name", "service account"),
            "folder_name": folder.get("name", "All Files"),
            "folder_id": self.root_folder_id,
            "auth_method": self.auth_method(),
        }

    # ---------------------------------------------------------- requests

    def _request(self, method, url, data=None, headers=None, raw=False):
        headers = dict(headers or {})
        headers["Authorization"] = f"Bearer {self.token()}"
        body = None
        if data is not None and not raw:
            body = json.dumps(data).encode()
            headers["Content-Type"] = "application/json"
        elif raw:
            body = data

        request = urllib.request.Request(url, data=body, headers=headers, method=method)
        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                payload = response.read()
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "ignore")[:400]
            if exc.code == 404:
                raise BoxError(f"Box could not find that item: {detail}") from exc
            if exc.code == 403:
                raise BoxError(
                    "Box denied access. The account this app authenticates as needs "
                    "at least Editor access to the folder. If you are using client "
                    "credentials with an enterprise id, the app's service account is "
                    "a separate user and the folder has to be shared with it."
                ) from exc
            raise BoxError(f"Box request failed ({exc.code}): {detail}") from exc
        return json.loads(payload) if payload else {}

    def _download(self, file_id):
        headers = {"Authorization": f"Bearer {self.token()}"}
        request = urllib.request.Request(f"{API}/files/{file_id}/content", headers=headers)
        with urllib.request.urlopen(request, timeout=300) as response:
            return response.read()

    # ----------------------------------------------------------- folders

    def list_folder(self, folder_id, limit=1000):
        items, offset = [], 0
        while True:
            page = self._request(
                "GET",
                f"{API}/folders/{folder_id}/items?limit={limit}&offset={offset}"
                f"&fields=id,name,type,size,modified_at",
            )
            entries = page.get("entries", [])
            items.extend(entries)
            offset += len(entries)
            if len(entries) < limit or offset >= page.get("total_count", 0):
                break
        return items

    def find_child(self, folder_id, name, kind=None):
        for item in self.list_folder(folder_id):
            if item["name"] == name and (kind is None or item["type"] == kind):
                return item
        return None

    def ensure_folder(self, name, parent_id):
        cache_key = (parent_id, name)
        if cache_key in self._folder_cache:
            return self._folder_cache[cache_key]
        existing = self.find_child(parent_id, name, "folder")
        if existing:
            self._folder_cache[cache_key] = existing["id"]
            return existing["id"]
        created = self._request(
            "POST", f"{API}/folders",
            {"name": name, "parent": {"id": str(parent_id)}},
        )
        self._folder_cache[cache_key] = created["id"]
        return created["id"]

    def cells_folder(self):
        return self.ensure_folder("cells", self.root_folder_id)

    # ------------------------------------------------------------ files

    def upload(self, folder_id, name, content):
        """Upload, or add a new version if the name is already taken."""
        if isinstance(content, str):
            content = content.encode("utf-8")

        existing = self.find_child(folder_id, name, "file")
        url = (
            f"{UPLOAD_API}/files/{existing['id']}/content"
            if existing
            else f"{UPLOAD_API}/files/content"
        )
        attributes = (
            {"name": name}
            if existing
            else {"name": name, "parent": {"id": str(folder_id)}}
        )

        boundary = f"----afm{uuid.uuid4().hex}"
        mime = mimetypes.guess_type(name)[0] or "application/octet-stream"
        body = io.BytesIO()
        body.write(f"--{boundary}\r\n".encode())
        body.write(b'Content-Disposition: form-data; name="attributes"\r\n')
        body.write(b"Content-Type: application/json\r\n\r\n")
        body.write(json.dumps(attributes).encode() + b"\r\n")
        body.write(f"--{boundary}\r\n".encode())
        body.write(
            f'Content-Disposition: form-data; name="file"; filename="{name}"\r\n'.encode()
        )
        body.write(f"Content-Type: {mime}\r\n\r\n".encode())
        body.write(content)
        body.write(f"\r\n--{boundary}--\r\n".encode())

        result = self._request(
            "POST", url, data=body.getvalue(), raw=True,
            headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        )
        entries = result.get("entries", [])
        return entries[0] if entries else result

    def shared_link(self, file_id, access="company"):
        """
        A link the browser can open.

        ``company`` keeps it inside the university, which is the right default
        for unpublished data; ``open`` would make it public to anyone with the
        URL.
        """
        result = self._request(
            "PUT", f"{API}/files/{file_id}?fields=shared_link",
            {"shared_link": {"access": access}},
        )
        link = result.get("shared_link") or {}
        return link.get("url"), link.get("download_url")

    # ----------------------------------------------------------- records

    def save_cell(self, record, curve_csv=None, thumbnail_png=None,
                  video_bytes=None, video_name="video.mp4"):
        """
        Write one cell's folder, then add it to the index.

        The record goes up first: if anything later fails, the cell still
        exists and is complete enough to be recovered by rebuilding the index.
        """
        cell_id = str(record["cell_id"]).strip()
        if not cell_id:
            raise BoxError("The cell needs a name before it can be saved.")

        folder_id = self.ensure_folder(cell_id, self.cells_folder())
        record = dict(record)
        record["box_folder_id"] = folder_id

        if curve_csv is not None:
            self.upload(folder_id, "curve.csv", curve_csv)
        if thumbnail_png is not None:
            info = self.upload(folder_id, "thumbnail.png", thumbnail_png)
            record["thumbnail_file_id"] = info.get("id")
        if video_bytes is not None:
            info = self.upload(folder_id, video_name, video_bytes)
            record["video_file_id"] = info.get("id")
            try:
                url, _ = self.shared_link(info["id"])
                record["video_url"] = url
            except BoxError:
                record["video_url"] = ""

        self.upload(folder_id, "record.json", json.dumps(record, indent=2, default=str))
        self.append_to_index(record)
        return record

    def load_cell(self, cell_id):
        """Return a cell's record and its curve, or None if it is not there."""
        folder = self.find_child(self.cells_folder(), str(cell_id), "folder")
        if not folder:
            return None
        record, curve = None, None
        for item in self.list_folder(folder["id"]):
            if item["name"] == "record.json":
                record = json.loads(self._download(item["id"]).decode("utf-8"))
            elif item["name"] == "curve.csv":
                curve = self._download(item["id"]).decode("utf-8")
        if record is not None:
            record["curve_csv"] = curve
        return record

    def thumbnail_bytes(self, file_id):
        try:
            return self._download(file_id)
        except Exception:
            return None

    # ------------------------------------------------------------- index

    INDEX_NAME = "index.csv"

    def index_columns(self):
        return [
            "cell_id", "date", "cell_type", "cell_height_um", "spring_constant_N_per_m",
            "invols_nm_per_V", "coupling", "procedure", "Em_MPa", "Ec_kPa", "En_kPa",
            "r_squared", "epsilon_min", "epsilon_max", "n_points", "operator", "notes",
            "video_url", "thumbnail_file_id", "box_folder_id", "saved_at",
        ]

    def load_index(self):
        """The index as a DataFrame, empty if there is not one yet."""
        import pandas as pd

        item = self.find_child(self.root_folder_id, self.INDEX_NAME, "file")
        if not item:
            return pd.DataFrame(columns=self.index_columns())
        try:
            text = self._download(item["id"]).decode("utf-8")
            return pd.read_csv(io.StringIO(text))
        except Exception:
            return pd.DataFrame(columns=self.index_columns())

    def append_to_index(self, record):
        import pandas as pd

        frame = self.load_index()
        row = {column: record.get(column, "") for column in self.index_columns()}
        frame = frame[frame.get("cell_id", pd.Series(dtype=str)) != record["cell_id"]] \
            if "cell_id" in frame.columns else frame
        frame = pd.concat([frame, pd.DataFrame([row])], ignore_index=True)
        self.upload(self.root_folder_id, self.INDEX_NAME, frame.to_csv(index=False))
        return frame

    def rebuild_index(self, progress=None):
        """
        Rebuild the index by reading every record.json.

        Slower than the cache, but it is the recovery path: the per-cell records
        are the truth, so this can always reconstruct a lost or stale index.
        """
        import pandas as pd

        folders = [i for i in self.list_folder(self.cells_folder()) if i["type"] == "folder"]
        rows = []
        for n, folder in enumerate(folders, start=1):
            if progress:
                progress(n, len(folders), folder["name"])
            item = self.find_child(folder["id"], "record.json", "file")
            if not item:
                continue
            try:
                record = json.loads(self._download(item["id"]).decode("utf-8"))
            except Exception:
                continue
            rows.append({column: record.get(column, "") for column in self.index_columns()})

        frame = pd.DataFrame(rows, columns=self.index_columns())
        self.upload(self.root_folder_id, self.INDEX_NAME, frame.to_csv(index=False))
        return frame


def store_from_secrets(st, root_folder_id=None):
    """Build a store from ``st.secrets['box']``, or None when unconfigured."""
    try:
        config = dict(st.secrets.get("box", {}))
    except Exception:
        config = {}
    if not config:
        return None
    if root_folder_id:
        config["root_folder_id"] = root_folder_id
    return BoxStore(config)
